### ISSUE TITLE
Error setting up olarm intergration

### ISSUE THREAD

**Issue by muhammadqasimc** [rainepretorius/olarm-ha-integration#1]
**Im getting the following in the logs.**
I have followed the documentation, and my key and ID is correct. Im not sure where to start debugging, perhaps you can shed some light on this, that would be highly appreciated.

```
Logger: homeassistant.config_entries
Source: helpers/entity_component.py:166
First occurred: 2:50:32 PM (1 occurrences)
Last logged: 2:50:32 PM

Error setting up entry Olarm Sensors for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 169, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 166, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
```

**As well as** 

```
Logger: homeassistant.components.binary_sensor
Source: custom_components/olarm_sensors/olarm_api.py:219
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 2:50:23 PM (1 occurrences)
Last logged: 2:50:23 PM

Error while setting up olarm_sensors platform for binary_sensor
Traceback (most recent call last):
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 122, in get_panel_states
    if olarm_state["areas"][1] == "arm":
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/olarm_sensors/binary_sensor.py", line 28, in async_setup_entry
    await coordinator.async_get_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 58, in async_get_data
    self.panel_data = await self.api.get_panel_states()
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 219, in get_panel_states
    except Exception(BaseException):
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by rainepretorius** [comment]
Please remove the integration and redo the setup. It seems that one of the values did not save.
