### ISSUE TITLE
[Bug]: Error setting up entry Olarm Sensors for olarm_sensors

### ISSUE THREAD

**Issue by molesza** [rainepretorius/olarm-ha-integration#108]
### Contact Details

myles.macaulay@gmail.com

### What happened?

Cant get the integration to load

### Version

2.0.1

### Relevant log output form Home Assistant

```shell
2024-04-22 12:00:56.398 INFO (MainThread) [custom_components.olarm_sensors] Setting up Olarm device (Max and myles) with device id: 79355f78-7fdd-448d-8876-a044c7e19a56
2024-04-22 12:00:57.046 WARNING (MainThread) [olarm_api_rainepretorius] This device's area names have not been set up in Olarm, generating automatically
2024-04-22 12:00:57.046 WARNING (MainThread) [olarm_api_rainepretorius] This device's area names have not been set up in Olarm, generating automatically
2024-04-22 12:00:57.046 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/__init__.py", line 106, in async_setup_entry
    await coordinator.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 136, in update_data
    self.panel_data = await self.api.get_panel_states(self.devices_json)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/olarm_api_rainepretorius/__init__.py", line 358, in get_panel_states
    if olarm_zones[area_num] == "":
       ~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
```

### Downloaded integration debug logs.

```shell
Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 10:37:58 (5 occurrences)
Last logged: 12:03:50

Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/__init__.py", line 106, in async_setup_entry
    await coordinator.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 136, in update_data
    self.panel_data = await self.api.get_panel_states(self.devices_json)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/olarm_api_rainepretorius/__init__.py", line 358, in get_panel_states
    if olarm_zones[area_num] == "":
       ~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range
```

**Comment by rainepretorius** [comment]
Update to the latest version.
