### ISSUE TITLE
[Bug]: Error initialising post update to HA 2024.6

### ISSUE THREAD

**Issue by martinjcxn** [rainepretorius/olarm-ha-integration#110]
### Contact Details

martinjcxn@gmail.com

### What happened?

Post update to the newest version of HA - the Olarm integration failed.

### Version

2.2.8

### Relevant log output form Home Assistant

```shell
2024-06-06 10:41:14.194 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/__init__.py", line 149, in async_setup_entry
    with open(
         ^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 123, in protected_loop_func
    raise_for_blocking_call(
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 42, in raise_for_blocking_call
    if check_allowed is not None and check_allowed(mapped_args):
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/block_async_io.py", line 28, in _check_file_allowed
    path = args[0] if type(args[0]) is str else str(args[0])  # noqa: E721
                           ~~~~^^^
IndexError: tuple index out of range
```

### Downloaded integration debug logs.

```shell
Having issue with debug logs, will update when I can find.
```

**Comment by witc-git** [comment]
Same issue after update, everything works again after restoring pre-update backup, thank goodness for that.
I forgot to download the log before restoring, but if you need more data I can update again a pull a log.

**Comment by Brandjohan** [comment]
Same my side. Broke immediately after upgrading. Restored back and going again.

**Comment by MrPrisoner** [comment]
From the logs it seems that the error occurs during setup where it writes to services.yaml. I'm not sure what the purpose of this file is, I commented out those lines, then olarm can start up correctly.

To apply to your integration, open custom_components/olarm_sensors/__init__.py and comment out lines 149-153. Then restart HA.

Changes on my fork for reference: https://github.com/rainepretorius/olarm-ha-integration/compare/main...MrPrisoner:olarm-ha-integration:main

**Comment by gjvanzyl** [comment]
Hey Guys

Running HA 2024.6 and latest 2.3.1 integration version. Still getting the "IndexError: list index out of range" error mentioned above.

Any ideas?

Logs below.

2024-06-11 12:00:57.819 WARNING (MainThread) [olarm_api_rainepretorius] This device's area names have not been set up in Olarm, generating automatically
2024-06-11 12:00:57.819 WARNING (MainThread) [olarm_api_rainepretorius] This device's area names have not been set up in Olarm, generating automatically
2024-06-11 12:00:57.820 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
return await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
result: _FlowResultT = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/olarm_sensors/config_flow.py", line 145, in async_step_user
await coordinator.update_data()
File "/config/custom_components/olarm_sensors/coordinator.py", line 136, in update_data
self.panel_data = await self.api.get_panel_states(self.devices_json)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/olarm_api_rainepretorius/__init__.py", line 358, in get_panel_states
if olarm_zones[area_num] == "":
~~~~~~~~~~~^^^^^^^^^^
IndexError: list index out of range

**Comment by gjvanzyl** [comment]
Hi @rainepretorius 

Any ideas on why the above is happening with an initial setup?

Thanks bud

**Comment by rainepretorius** [comment]
Please update to 2.3.1 with Home Assistant 2024.6

**Comment by gjvanzyl** [comment]
> Hi @gjvanzyl Please update to 2.3.1 with Home Assistant 2024.6. They changed stuff with Home Assistant that breaks an integration if it does not run in a thread. So version of the integrations of Olarm Sensors before 2.3.1 will break with Core 2024.6

Thanks @rainepretorius. I already have both latest builds installed. 

Any other suggestions?

**Comment by gjvanzyl** [comment]
Hi @rainepretorius 

Managed to find the issue. My areas/partitions had no names inside Olarm; was still using default Area1,2,3 etc so I presume the setup script was having issues creating unique identifiers for them as per the last part of the log I shared above. 

Potentially something to add a catch for.

**Comment by martinjcxn** [comment]
Just to add that the newest update has resolved this issue for me. Thanks @rainepretorius 

Also, for completeness @MrPrisoner's solution did work as an interim measure until the update became available.

I am going to close this issue on the basis of it being resolved.
