### ISSUE TITLE
String Index: PGM

### ISSUE THREAD

**Issue by rainepretorius** [rainepretorius/olarm-ha-integration#25]
HI Raine,

Somewhere along the way I seem to have lost connectivity. Having deleted everything and re-installed the latest version, I now get the error below and system is immediately  unavailable.

![image](https://user-images.githubusercontent.com/58702667/230316044-dad5349c-90b7-4fd3-8035-4ff83db288c1.png)

2023-04-06 10:10:00.692 ERROR (MainThread) [custom_components.olarm_sensors.coordinator] Unexpected error fetching Olarm Coordinator (XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX) data: string index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 144, in _async_update_data
    return await self.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 127, in update_data
    self.pgm_data = await self.api.get_pgm_zones(devices_json)
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 267, in get_pgm_zones
    enabled = pgm_setup[i][0] == "1"
IndexError: string index out of range

_Originally posted by @JTUBB69 in https://github.com/rainepretorius/olarm-ha-integration/discussions/23#discussioncomment-5540930_

**Comment by rainepretorius** [comment]
This issue has been fixed in the new version 1.1.9
