### ISSUE TITLE
Installed ver 2.02 only shows 2 entities

### ISSUE THREAD

**Issue by pickwit** [rainepretorius/olarm-ha-integration#32]
Hi. I did a fresh re-install to ver 2.02 and only get 2 entities which are unavailable. (see screenshots).  Please assist.
[Olarm.pdf](https://github.com/rainepretorius/olarm-ha-integration/files/11183023/Olarm.pdf)
[olarm2.pdf](https://github.com/rainepretorius/olarm-ha-integration/files/11183024/olarm2.pdf)

**Comment by jonathankretzmer** [comment]
Are you able to provide the exception being display in your HomeAssistant log?

**Comment by pickwit** [comment]
[log.pdf](https://github.com/rainepretorius/olarm-ha-integration/files/11184969/log.pdf)

**Comment by rainepretorius** [comment]
> [log.pdf](https://github.com/rainepretorius/olarm-ha-integration/files/11184969/log.pdf)

Hi @pickwit , That is the device page and not the logs. The logs can be found here:
http://<your_home_assistant_ip>::8123/config/logs/?filter=olarm_sensors

**Comment by pickwit** [comment]
[HA Core Log.pdf](https://github.com/rainepretorius/olarm-ha-integration/files/11184973/HA.Core.Log.pdf)

**Comment by rainepretorius** [comment]
Can you please click on each one of those errors and sent through the popup?

**Comment by rainepretorius** [comment]
It seems that it is trying to get data that does not exist, but I cannot yet see where.

**Comment by pickwit** [comment]
This error originated from a custom integration.

Logger: custom_components.olarm_sensors.coordinator
Source: custom_components/olarm_sensors/olarm_api.py:263
Integration: Olarm Sensors (documentation, issues)
First occurred: 8:50:44 AM (266 occurrences)
Last logged: 9:13:00 AM

Unexpected error fetching Olarm Coordinator (735ee402-1f7d-44d9-9773-9e22a840f4c3) data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 145, in _async_update_data
    return await self.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 128, in update_data
    self.pgm_data = await self.api.get_pgm_zones(devices_json)
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 263, in get_pgm_zones
    state = str(pgm_state[i]).lower() == "a"
IndexError: list index out of range

**Comment by pickwit** [comment]
Logger: homeassistant.components.button
Source: custom_components/olarm_sensors/olarm_api.py:263
Integration: Button (documentation, issues)
First occurred: 8:50:40 AM (2 occurrences)
Last logged: 9:03:25 AM

Error while setting up olarm_sensors platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/olarm_sensors/button.py", line 26, in async_setup_entry
    await coordinator.async_get_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 153, in async_get_data
    return await self.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 128, in update_data
    self.pgm_data = await self.api.get_pgm_zones(devices_json)
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 263, in get_pgm_zones
    state = str(pgm_state[i]).lower() == "a"
IndexError: list index out of range

**Comment by pickwit** [comment]
Logger: homeassistant.components.binary_sensor
Source: custom_components/olarm_sensors/olarm_api.py:263
Integration: Binary sensor (documentation, issues)
First occurred: 8:50:41 AM (2 occurrences)
Last logged: 9:03:25 AM

Error while setting up olarm_sensors platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/olarm_sensors/binary_sensor.py", line 31, in async_setup_entry
    await coordinator.async_get_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 153, in async_get_data
    return await self.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 128, in update_data
    self.pgm_data = await self.api.get_pgm_zones(devices_json)
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 263, in get_pgm_zones
    state = str(pgm_state[i]).lower() == "a"
IndexError: list index out of range

**Comment by pickwit** [comment]
These are the 3 errors copied and pasted

**Comment by rainepretorius** [comment]
Thanks @pickwit ,
I will try to implement a fix for this asap. Apologies for the continued outage due to certain added features.

**Comment by pickwit** [comment]
No problem Raine. You are doing a sterling job! Thanks for integrating Olarm into HA

**Comment by pickwit** [comment]
Issue has been resolved with version 2.04! 

Thanks Raine

**Comment by rainepretorius** [comment]
Glad to hear that it is working. Sorry for the delayed response as I broke my finger the pas week.
