### ISSUE TITLE
Error post upgrade

### ISSUE THREAD

**Issue by maritzhome1** [rainepretorius/olarm-ha-integration#34]
Hi Raine - first off, thanks for the work on this, been working great.

I pulled in the updates yesterday and post that am getting errors.

Below is the log.

Logger: aiohttp.server
Source: custom_components/olarm_sensors/config_flow.py:142
Integration: Olarm Sensors ([documentation](https://github.com/rainepretorius/olarm-ha-integration/blob/main/README.md), [issues](https://github.com/rainepretorius/olarm-ha-integration/issues))
First occurred: 07:49:04 (2 occurrences)
Last logged: 07:52:33

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 218, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/olarm_sensors/config_flow.py", line 193, in async_step_init
    data_schema=self._get_schema(),
  File "/config/custom_components/olarm_sensors/config_flow.py", line 142, in _get_schema
    if self.config_entry.data[CONF_ALARM_CODE] is None:
KeyError: 'olarm_arm_code'

**Comment by jonathankretzmer** [comment]
When you are configuring it for the first time are you leaving the pin code blank? I've found that leaving the default value in there is better and is used to signal to the app that you don't wish to use one.

**Comment by rainepretorius** [comment]
As said in the release notes of version 1.1.8. The setup needs to be redone before it will work again. THis is due to the feature being added for the option to use a code for the actions (arm, sleep, stay and disarm).
