### ISSUE TITLE
Unexpected error fetching Olarm Coordinator data: 'pgmLimit'

### ISSUE THREAD

**Issue by rbusschau** [rainepretorius/olarm-ha-integration#42]
Hi

I've just installed your HA Olarm integration and it sounds great, thanks! I get the following error once I have installed the HACS component, restarted HA and entered my API key:

Unexpected error fetching Olarm Coordinator data: 'pgmLimit'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 154, in _async_update_data
    return await self.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 137, in update_data
    self.pgm_data = await self.api.get_pgm_zones(devices_json)
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 268, in get_pgm_zones
    pgm_limit = devices_json["deviceProfile"]["pgmLimit"]
KeyError: 'pgmLimit'

Here is the info from https://apiv4.olarm.co/api/v4/devices/my-device-id
[OlarmAPI.txt](https://github.com/rainepretorius/olarm-ha-integration/files/11334640/OlarmAPI.txt)

**Comment by rainepretorius** [comment]
Hi @rbusschau ,
I will look into it this weekend.
