### ISSUE TITLE
[Bug]: JSON issue

### ISSUE THREAD

**Issue by tommiedw** [rainepretorius/olarm-ha-integration#63]
### Contact Details

tommiedewaal@gmail.com

### What happened?

Hi Raine

Everytime I try and add the Olarm back into HA I get the below error. Tried totally removing the device also creating a new API key making sure I don't mess around with the refresh intervals etc.

Not sure why its complaining about unexpected mimetype in the JSON code.

Thanks

### Version

2.1.7

### Relevant log output

```shell
File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://apiv4.olarm.co/api/v4/devices/4df3375f-41b8-4338-b965-9f3a3ea1dc64')
```

**Comment by rainepretorius** [comment]
Hi @tommiedw ,

Does this error disappear after a while or is it constant?

**Comment by tommiedw** [comment]
It comes up as soon as I add the Olarm integration (and nothing after that) it showed "Failed to setup" immediately after that...

It use to work before a while ago. Since it started with this problem, I just left it and waited for an update release.

Thought I share if anyone else was having the same issue :) 

Also just wanted to note, I have two Olarm devices. One for my Texecom 832 and one for my Nemtek electric fence

Full dump
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/__init__.py", line 90, in async_setup_entry
    await coordinator.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 96, in update_data
    devices_json = await self.api.get_device_json()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 54, in get_device_json
    return await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://apiv4.olarm.co/api/v4/devices/4df3375f-41b8-4338-b965-9f3a3ea1dc64')

**Comment by Chris-777** [comment]
I'm having the same issue. Apologies for posting in the wrong place:
https://github.com/rainepretorius/olarm-ha-integration/discussions/59

**Comment by rainepretorius** [comment]
Hi @Chris-777 and @tommiedw,

I am planning to incorporate a diagnostic feature into the integration that will collect all relevant data to aid in bug fixing both now and in the future. My goal is to release the update containing this feature either later today or tomorrow morning.

**Comment by tommiedw** [comment]
Thanks for all the efforts, its appreciated. The diagnostic feature would be awesome, will help with troubleshooting for sure.

**Comment by chriscc12345** [comment]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/olarm_sensors/olarm_api.py:54
Integration: Olarm Sensors (documentation, issues)
First occurred: 8:45:01 PM (2 occurrences)
Last logged: 8:45:22 PM

Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/__init__.py", line 90, in async_setup_entry
    await coordinator.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 96, in update_data
    devices_json = await self.api.get_device_json()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 54, in get_device_json
    resp = await response.json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://apiv4.olarm.co/api/v4/devices/8be0f51b-f559-45d6-af6a-09efa5dba872')

**Comment by jakesie1309** [comment]
Hi there, same this side. Also have two Olarm devices. Before the update it work, but only with the second device. For some reason it did not want to pick my main device. Saw the update and also thought, Ye, finally sorted :-) however also getting the same as @chriscc12345 
<img width="1138" alt="Screenshot 2023-06-14 at 19 17 43" src="https://github.com/rainepretorius/olarm-ha-integration/assets/46168037/ed92427d-23e4-428f-86b8-c787089c43ef">
<img width="1307" alt="Screenshot 2023-06-14 at 19 18 46" src="https://github.com/rainepretorius/olarm-ha-integration/assets/46168037/ab95b209-b82b-4311-8167-4856af973a4d">

**Comment by jakesie1309** [comment]
Ok, did a full restart again, and back to almost working. However it is not working with my second Olarm sensor
See below, picking up the 93 sensor just fine, but nothing on the main device

Any idea?
<img width="1340" alt="Screenshot 2023-06-14 at 19 24 23" src="https://github.com/rainepretorius/olarm-ha-integration/assets/46168037/620c2b95-b56f-493a-b3be-cbcea8522697">
<img width="1340" alt="Screenshot 2023-06-14 at 19 23 51" src="https://github.com/rainepretorius/olarm-ha-integration/assets/46168037/5f95eb3d-beae-48c8-9336-51a16eab594a">

**Comment by blackbasilisk** [comment]
Hey man. Super excited to have this working. Thank you so much for your effort!! 

Looks like I am having the same issue.

2023-06-14 20:48:16.818 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/olarm_sensors/__init__.py", line 46, in async_setup_entry
await update_listener(hass, config_entry)
File "/config/custom_components/olarm_sensors/__init__.py", line 224, in update_listener
options[OLARM_DEVICES] = devices
^^^^^^^
UnboundLocalError: cannot access local variable 'options' where it is not associated with a value
2023-06-14 20:48:52.577 ERROR (MainThread) [frontend.js.latest.202306080] http://192.168.1.241:8123/frontend_latest/17827-INquOPjPYjM.js:1:92699 TypeError: null is not an object (evaluating 'this.contentElement.removeEventListener')
2023-06-14 20:50:18.923 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/olarm_sensors/__init__.py", line 46, in async_setup_entry
await update_listener(hass, config_entry)
File "/config/custom_components/olarm_sensors/__init__.py", line 224, in update_listener
options[OLARM_DEVICES] = devices
^^^^^^^
UnboundLocalError: cannot access local variable 'options' where it is not associated with a value
2023-06-14 20:52:45.675 ERROR (MainThread) [frontend.js.latest.202306080] http://192.168.1.241:8123/frontend_latest/17827-INquOPjPYjM.js:1:92699 TypeError: null is not an object (evaluating 'this.contentElement.removeEventListener')
2023-06-14 20:53:43.255 INFO (MainThread) [custom_components.olarm_sensors] Setting up Olarm device (Angela Home) with device id: 4518c631-3d87-48d8-8bc4-93be23e4e1bd
2023-06-14 20:53:43.456 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/olarm_sensors/__init__.py", line 90, in async_setup_entry
await coordinator.update_data()
File "/config/custom_components/olarm_sensors/coordinator.py", line 96, in update_data
devices_json = await self.api.get_device_json()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/olarm_sensors/olarm_api.py", line 54, in get_device_json
resp = await response.json()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1104, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://apiv4.olarm.co/api/v4/devices/4518c631-3d87-48d8-8bc4-93be23e4e1bd')

**Comment by blackbasilisk** [comment]
I have a single primary device, but 3 x secondary devices Ie 3 x devices that are shared with me. 

Might be relevant to know that it doesn’t seem to save the specific device I want to monitor sensors for under the ‘configure’ form. I would select the primary device and submit but when I view again it is not selected:

 
![image](https://github.com/rainepretorius/olarm-ha-integration/assets/87368248/9b20aa79-398a-4c66-8ed7-d72a8b4f600b)

**Comment by blackbasilisk** [comment]
I kept fiddling and managed to get it to work. I deleted one of the devices that were offline,  I then (because I was bored), added avatars to each zone on Olarm app, Regenerated api key, and then reloaded the integration a few times and then suddenly it worked.

not sure. Either way. Seems to be ok now. Will add alarm panel card etc. and send feedback if any further issues.

Dave

**Comment by zakattack-za** [comment]
Hi @rainepretorius 

Thanks for your work on this. Let me know if you need some help with troubleshooting this issue and / or debug logs.

Version 2.1.8 on fully up to date HA

Same issue for me:

First error on reload / reinstall:
```
ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/__init__.py", line 46, in async_setup_entry
    await update_listener(hass, config_entry)
  File "/config/custom_components/olarm_sensors/__init__.py", line 224, in update_listener
    options[OLARM_DEVICES] = devices
    ^^^^^^^
UnboundLocalError: cannot access local variable 'options' where it is not associated with a value
```
Second log entry:
`ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/__init__.py", line 46, in async_setup_entry
    await update_listener(hass, config_entry)
  File "/config/custom_components/olarm_sensors/__init__.py", line 224, in update_listener
    options[OLARM_DEVICES] = devices
                             ^^^^^^^
UnboundLocalError: cannot access local variable 'options' where it is not associated with a value
`

Also have the two Olarm devices. 
Selecting either device in the Configuration menu and clicking submit does not save the selection (when navigating back to Configuration no device is selected). API key persists on Submit.

I've tried:
Delete / reinstall integration.
Cleaning up stale configuration entries manually
Regenerating API keys and reloading integration

**Comment by zakattack-za** [comment]
@rainepretorius 

This fixed it for me in __init__.py:
![image](https://github.com/rainepretorius/olarm-ha-integration/assets/136877380/ba62e3a4-4c42-4106-a426-30ac031db818)

**Comment by jakesie1309** [comment]
@zakattack-za, only one of my olarm devices are pulling in. for some reason the main one does not pull in. will wait for @rainepretorius to see if he has a fix. when manually creating the sensors it works fine.

**Comment by jakesie1309** [comment]
@rainepretorius and @zakattack-za, ok so my is working 100%. Did not do anything special to the code, basically I was busy working through all my addin, busy cleaning up and fix all log errors for my ha instance and after a round 4 restarts, I notice that olarm was up and running. hopefully it does not bomb out after a restart but will keep you guys posted

**Comment by rainepretorius** [comment]
> @rainepretorius and @zakattack-za, ok so my is working 100%. Did not do anything special to the code, basically I was busy working through all my addins, busy cleaning up and fixing all log errors for my ha instance and after a round 4 restarts, I notice that olarm was up and running. hopefully it does not bomb out after a restart but will keep you guys posted

Hi @jakesie1309 ,
Yes. It depends on Olarm and how they see a request. If they think there is a too frequent call they block it for a while and then it will sometimes randomly start to work again. Version 2.1.7 and 2.1.7 is exactly the same. 2.1.8 just allows jou to download the logs.

**Comment by rainepretorius** [comment]
> Hi @rainepretorius 
> 
> Thanks for your work on this. Let me know if you need some help with troubleshooting this issue and / or debug logs.
> 
> Version 2.1.8 on fully up to date HA
> 
> Same issue for me:
> 
> Error on reload / reinstall:
> ```
> ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/olarm_sensors/__init__.py", line 46, in async_setup_entry
>     await update_listener(hass, config_entry)
>   File "/config/custom_components/olarm_sensors/__init__.py", line 224, in update_listener
>     options[OLARM_DEVICES] = devices
>     ^^^^^^^
> UnboundLocalError: cannot access local variable 'options' where it is not associated with a value
> ```
> 
> Also have the two Olarm devices. 
> Selecting either device in the Configuration menu and clicking submit does not save the selection (when navigating back to Configuration no device is selected). API key persists on Submit.
> 
> I've tried:
> Delete / reinstall integration.
> Cleaning up stale configuration entries manually
> Regenerating API keys and reloading integration
> 
> 
> 
> 
> 

Will look into this error. I should repky to the cause and maybe have a fix tomorrow.

**Comment by rainepretorius** [comment]
> @zakattack-za, only one of my olarm devices are pulling in. for some reason the main one does not pull in. will wait for @rainepretorius to see if he has a fix. when manually creating the sensors it works fine.

Hi @jakesie1309 ,
Can you send me the diagnostic file for the integration? And the name of the main device. I will then check to see what is happening.

**Comment by mikesierra555** [comment]
> @rainepretorius and @zakattack-za, ok so my is working 100%. Did not do anything special to the code, basically I was busy working through all my addins, busy cleaning up and fixing all log errors for my ha instance and after a round 4 restarts, I notice that olarm was up and running. hopefully it does not bomb out after a restart but will keep you guys posted

I had the same errors as others with 2 devices (I had 6, deleted 4). I'd already tried every combination of new api key, delete, reboot, restore HA. 

Eventually tried cleaning up my error log like @jakesie1309 . That worked. Magic.

**Comment by chriscc12345** [comment]
![Screenshot 2023-06-19 at 22 20 38](https://github.com/rainepretorius/olarm-ha-integration/assets/60073902/2c467f90-702b-4453-a783-46d87f900faf)

**Comment by abrievanaardt** [comment]
For some reason, the `aiohttp`  client receives a `Content-Type` HTTP header with a value of `text/plain` on the response. I can't reproduce this behaviour with a simple `curl` command, but it could be caused by one or more of the headers the client is sending.

Disabling the content type check on the `response.json()`  call (i.e. `resp = await response.json(content_type=None`) works for me (after a restart of course).

**Comment by rainepretorius** [comment]
> For some reason, the `aiohttp`  client receives a `Content-Type` HTTP header with a value of `text/plain` on the response. I can't reproduce this behaviour with a simple `curl` command, but it could be caused by one or more of the headers the client is sending.
> 
> Disabling the content type check on the `response.json()`  call (i.e. `resp = await response.json(content_type=None`) works for me (after a restart of course).

Cool will implement this change and we all can check if this error then persists. I also cannot reproduse the error if I do not use pythons aiohttp library.
