### ISSUE TITLE
[Bug]: The first 32 zones are not available in HA

### ISSUE THREAD

**Issue by blackbasilisk** [rainepretorius/olarm-ha-integration#73]
### Contact Details

dave@coates.co.za

### What happened?

Alarm panel: IDS x64

Zone 1 - 32 is not available in HA at all.

We are using zones 1-10 and then again zone 33-40 on our panel (no idea why our installed did it this way!!)

I first let it and thought maybe it just needs some time to rest ;), but weeks later still the same.  Removed the integration, re-added and same result. 

[olarm_ha_log.txt](https://github.com/rainepretorius/olarm-ha-integration/files/12437590/olarm_ha_log.txt)

[olarm_ha_log2.txt](https://github.com/rainepretorius/olarm-ha-integration/files/12437629/olarm_ha_log2.txt)

### Version

2.0.1

### Relevant log output

```shell
2023-08-25 11:12:54.571 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 249, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/diagnostics.py", line 10, in async_get_config_entry_diagnostics
    return await async_get_device_diagnostics(hass, entry, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/olarm_sensors/diagnostics.py", line 56, in async_get_device_diagnostics
    device["deviceProfile"].pop("fenceLabels")
KeyError: 'fenceLabels'
```

**Comment by rainepretorius** [comment]
Hi, Can you update the integration please and see if it persists? The newest version is 2.2.2
